sonar.projectKey=hrms
sonar.projectName=hrms
sonar.sources=app,components,lib
sonar.tests=__tests__,e2e
sonar.exclusions=.next/**,node_modules/**,coverage/**,storybook-static/**
sonar.typescript.tsconfigPath=tsconfig.json
