// Employees Page - Manage employee records
// Features: Add new employee, view all employees, delete employees
// Updated: Added department dropdown with custom option for easier data entry
'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'

// Default departments - stored as plain text in database
// Why plain text: Keeps schema simple, no separate departments table needed
// This is interview-friendly and easy to explain
const DEFAULT_DEPARTMENTS = [
    'Engineering',
    'HR',
    'Sales',
    'Marketing',
    'Operations',
]

export default function EmployeesPage() {
    // State for employees list and form data
    const [employees, setEmployees] = useState([])
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState(null)
    const [formError, setFormError] = useState(null)
    const [submitting, setSubmitting] = useState(false)

    // Form state (employee_id is auto-generated by backend)
    const [formData, setFormData] = useState({
        full_name: '',
        email: '',
        department: '',
        customDepartment: '' // For custom department input
    })

    // Track whether user wants to use custom department
    const [useCustomDept, setUseCustomDept] = useState(false)

    // Fetch all employees on page load
    useEffect(() => {
        fetchEmployees()
    }, [])

    const fetchEmployees = async () => {
        try {
            setLoading(true)
            setError(null)
            const res = await fetch('/api/employees')
            const data = await res.json()

            if (!res.ok) {
                throw new Error(data.error || 'Failed to fetch employees')
            }

            setEmployees(data)
        } catch (err) {
            setError(err.message)
        } finally {
            setLoading(false)
        }
    }

    // Handle form input changes
    const handleChange = (e) => {
        setFormData({ ...formData, [e.target.name]: e.target.value })
    }

    // Handle form submission
    const handleSubmit = async (e) => {
        e.preventDefault()
        setFormError(null)
        setSubmitting(true)

        // Determine which department to use
        // Priority: custom department > dropdown selection
        const department = useCustomDept && formData.customDepartment.trim()
            ? formData.customDepartment.trim()
            : formData.department

        if (!department) {
            setFormError('Please select or enter a department')
            setSubmitting(false)
            return
        }

        try {
            const res = await fetch('/api/employees', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    full_name: formData.full_name,
                    email: formData.email,
                    department
                })
            })

            const data = await res.json()

            if (!res.ok) {
                throw new Error(data.error || 'Failed to add employee')
            }

            // Reset form and refresh list
            setFormData({ full_name: '', email: '', department: '', customDepartment: '' })
            setUseCustomDept(false)
            fetchEmployees()
        } catch (err) {
            setFormError(err.message)
        } finally {
            setSubmitting(false)
        }
    }

    // Handle employee deletion
    const handleDelete = async (employee_id) => {
        if (!confirm('Are you sure you want to delete this employee?')) return

        try {
            const res = await fetch(`/api/employees?employee_id=${employee_id}`, {
                method: 'DELETE'
            })

            if (!res.ok) {
                const data = await res.json()
                throw new Error(data.error || 'Failed to delete employee')
            }

            fetchEmployees()
        } catch (err) {
            alert(err.message)
        }
    }

    return (
        <main className="min-h-screen bg-gray-50">
            {/* Header */}
            <header className="bg-white shadow-sm">
                <div className="max-w-4xl mx-auto px-4 py-6">
                    <div className="flex items-center justify-between">
                        <div>
                            <h1 className="text-2xl font-bold text-gray-900">Employees</h1>
                            <p className="text-gray-600 mt-1">Manage employee records</p>
                        </div>
                    </div>
                </div>
            </header>

            <div className="max-w-4xl mx-auto px-4 py-8">
                {/* Add Employee Form */}
                <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-200 mb-8">
                    <h2 className="text-lg font-semibold text-gray-800 mb-4">Add New Employee</h2>

                    {formError && (
                        <div className="mb-4 p-3 bg-red-50 border border-red-200 text-red-700 rounded">
                            {formError}
                        </div>
                    )}

                    <form onSubmit={handleSubmit} className="space-y-4">
                        <div className="grid md:grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Full Name
                                </label>
                                <input
                                    type="text"
                                    name="full_name"
                                    value={formData.full_name}
                                    onChange={handleChange}
                                    required
                                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                                    placeholder="Enter full name"
                                />
                            </div>

                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Email
                                </label>
                                <input
                                    type="email"
                                    name="email"
                                    value={formData.email}
                                    onChange={handleChange}
                                    required
                                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                                    placeholder="name@gmail.com"
                                />
                            </div>
                        </div>

                        {/* Department Selection */}
                        <div className="grid md:grid-cols-2 gap-4">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Department
                                </label>
                                <select
                                    name="department"
                                    value={formData.department}
                                    onChange={handleChange}
                                    disabled={useCustomDept}
                                    className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:bg-gray-100 disabled:cursor-not-allowed"
                                >
                                    <option value="">Select Department</option>
                                    {DEFAULT_DEPARTMENTS.map((dept) => (
                                        <option key={dept} value={dept}>
                                            {dept}
                                        </option>
                                    ))}
                                </select>
                            </div>

                            {/* Custom Department Option */}
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">
                                    Or Add Custom Department
                                </label>
                                <div className="flex gap-2">
                                    <input
                                        type="text"
                                        name="customDepartment"
                                        value={formData.customDepartment}
                                        onChange={(e) => {
                                            handleChange(e)
                                            // Auto-enable custom if user types
                                            if (e.target.value.trim()) {
                                                setUseCustomDept(true)
                                            }
                                        }}
                                        onFocus={() => setUseCustomDept(true)}
                                        className="flex-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                                        placeholder="Enter custom department"
                                    />
                                    {useCustomDept && (
                                        <button
                                            type="button"
                                            onClick={() => {
                                                setUseCustomDept(false)
                                                setFormData({ ...formData, customDepartment: '' })
                                            }}
                                            className="px-3 py-2 text-gray-500 hover:text-gray-700"
                                        >
                                            ✕
                                        </button>
                                    )}
                                </div>
                                {useCustomDept && (
                                    <p className="text-xs text-blue-600 mt-1">Using custom department</p>
                                )}
                            </div>
                        </div>

                        <div>
                            <button
                                type="submit"
                                disabled={submitting}
                                className="w-full md:w-auto px-6 py-2 bg-blue-600 text-white font-medium rounded-md hover:bg-blue-700 disabled:bg-blue-400 disabled:cursor-not-allowed"
                            >
                                {submitting ? 'Adding...' : 'Add Employee'}
                            </button>
                        </div>
                    </form>
                </div>

                {/* Employees Table */}
                <div className="bg-white rounded-lg shadow-sm border border-gray-200">
                    <div className="px-6 py-4 border-b border-gray-200">
                        <h2 className="text-lg font-semibold text-gray-800">All Employees</h2>
                    </div>

                    {/* Loading State */}
                    {loading && (
                        <div className="p-8 text-center text-gray-500">
                            Loading employees...
                        </div>
                    )}

                    {/* Error State */}
                    {error && !loading && (
                        <div className="p-8 text-center">
                            <p className="text-red-600 mb-4">{error}</p>
                            <button
                                onClick={fetchEmployees}
                                className="px-4 py-2 bg-gray-100 text-gray-700 rounded hover:bg-gray-200"
                            >
                                Try Again
                            </button>
                        </div>
                    )}

                    {/* Empty State */}
                    {!loading && !error && employees.length === 0 && (
                        <div className="p-8 text-center text-gray-500">
                            No employees found. Add your first employee above.
                        </div>
                    )}

                    {/* Table */}
                    {!loading && !error && employees.length > 0 && (
                        <div className="overflow-x-auto">
                            <table className="w-full">
                                <thead className="bg-gray-50">
                                    <tr>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                                            Employee ID
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                                            Full Name
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                                            Email
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                                            Department
                                        </th>
                                        <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">
                                            Actions
                                        </th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-gray-200">
                                    {employees.map((emp) => (
                                        <tr key={emp.id} className="hover:bg-gray-50">
                                            <td className="px-6 py-4 text-sm text-gray-900">
                                                {emp.employee_id}
                                            </td>
                                            <td className="px-6 py-4 text-sm text-gray-900">
                                                {emp.full_name}
                                            </td>
                                            <td className="px-6 py-4 text-sm text-gray-600">
                                                {emp.email}
                                            </td>
                                            <td className="px-6 py-4 text-sm text-gray-600">
                                                {emp.department}
                                            </td>
                                            <td className="px-6 py-4 text-sm space-x-3">
                                                <Link
                                                    href={`/employees/${emp.employee_id}`}
                                                    className="text-blue-600 hover:text-blue-800"
                                                >
                                                    View
                                                </Link>
                                                <button
                                                    onClick={() => handleDelete(emp.employee_id)}
                                                    className="text-red-600 hover:text-red-800"
                                                >
                                                    Delete
                                                </button>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>
            </div>
        </main>
    )
}
